spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: 'true'
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: ricardo
    password: epam
  jpa:
    hibernate:
      ddl-auto: none
  output:
    ansi:
      enabled: ALWAYS
server:
  port: 8080

# OpenAPI (Swagger) Configuration
springdoc:
  api-docs:
    enabled: 'true'
  swagger-ui:
    enabled: 'true'
    path: /doc/swagger-ui.html

logging:
  level:
    root: info
    org:
      springframework:
        jdbc:
          datasource:
            init:
              ScriptUtils: debug