insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Manya', 'Whitcomb', 'Manya.Whitcomb', 'vbxowmkpue', false);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Shea', 'McFater', 'Shea.McFater', 'pmilyjaewb', false);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Miquela', 'Trembley', 'Miquela.Trembley', 'lvuhcyjdmw', true);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Roddy', 'Patman', 'Roddy.Patman', 'aulecriyox', true);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Betteann', 'Staten', 'Betteann.Staten', 'npwrbgzsom', false);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Robin', 'Harbottle', 'Robin.Harbottle', 'dienjrlgck', true);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Herminia', 'Blackesland', 'Herminia.Blackesland', 'dlizxycfbg', true);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Virginie', 'Francis', 'Virginie.Francis', 'pevaiwgqrl', true);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Kelbee', 'Gerbi', 'Kelbee.Gerbi', 'ltydnrpjoi', true);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Virge', 'Leachman', 'Virge.Leachman', 'hxipjkcvar', true);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Port', 'Othick', 'Port.Othick', 'eflogxsbty', true);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Luella', 'Chimes', 'Luella.Chimes', 'mcysrwifel', true);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Cassondra', 'Castilla', 'Cassondra.Castilla', 'ysoefulkjr', true);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Earl', 'Winwood', 'Earl.Winwood', 'eaqnofzhks', false);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Kit', 'Lendon', 'Kit.Lendon', 'rmhuedxygb', true);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Lindon', 'Chessel', 'Lindon.Chessel', 'djxqtyvbfc', false);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Claudette', 'DeAmbrosi', 'Claudette.De Ambrosi', 'goxmeydsbj', true);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Doris', 'Height', 'Doris.Height', 'aptjuwicdv', true);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Janessa', 'Creeghan', 'Janessa.Creeghan', 'wolmtpihqn', false);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Barb', 'Benion', 'Barb.Benion', 'omxdehbvcw', false);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Corenda', 'Filipponi', 'Corenda.Filipponi', 'lzqxijscat', false);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Ambrosius', 'Marklin', 'Ambrosius.Marklin', 'qufensxtmo', false);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Tandi', 'Blakiston', 'Tandi.Blakiston', 'okfwjayepi', true);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Felita', 'Benedek', 'Felita.Benedek', 'qhmgdzfrbw', false);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Jillian', 'Dottrell', 'Jillian.Dottrell', 'awpdzocfky', true);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Lynelle', 'Haruard', 'Lynelle.Haruard', 'ejaxqgwufv', true);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Tabbie', 'Arbon', 'Tabbie.Arbon', 'yvbjfeazlu', false);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Nannie', 'Parisot', 'Nannie.de la Valette Parisot', 'wnsfarbjot', false);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Tailor', 'Rigler', 'Tailor.Rigler', 'eajimdcvxk', true);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Erinn', 'Lafflin', 'Erinn.Lafflin', 'hdjbmcvgyt', true);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Jermayne', 'Beaze', 'Jermayne.Beaze', 'okmrfgbtix', true);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Alain', 'Ogborne', 'Alain.Ogborne', 'cugesyfkhq', true);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Monroe', 'Cranmer', 'Monroe.Cranmer', 'tjbfzcqrud', false);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Philippine', 'Beatson', 'Philippine.Beatson', 'urndkscqvt', true);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Bambie', 'Pelham', 'Bambie.Pelham', 'lmoacuqifp', false);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Ulises', 'Shillum', 'Ulises.Shillum', 'cgiorslnth', false);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Lemuel', 'Wait', 'Lemuel.Wait', 'wrzsnvechq', true);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Diena', 'Sayers', 'Diena.Sayers', 'ypmuwhefzk', false);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Rudd', 'Robbings', 'Rudd.Robbings', 'silztebojg', true);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Nathaniel', 'Swyn', 'Nathaniel.Swyn', 'jkdyvutlxa', false);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Sandy', 'Gasnell', 'Sandy.Gasnell', 'xzgoulvqtj', false);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Beverley', 'Costley', 'Beverley.Costley', 'qndcghvrau', true);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Elvina', 'Middleton', 'Elvina.Middleton', 'fmavxyhebp', false);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Constantia', 'Faithorn', 'Constantia.Faithorn', 'ekltucxdjs', true);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Jeana', 'Brosi', 'Jeana.Brosi', 'yspvdlagcw', true);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Odell', 'Lourens', 'Odell.Lourens', 'ptmioneqwh', true);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Lainey', 'Herrema', 'Lainey.Herrema', 'mlnbdjaytu', false);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Adrienne', 'Rosenbush', 'Adrienne.Rosenbush', 'mywzaxkfqo', false);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Doreen', 'Dachs', 'Doreen.Dachs', 'zmtsypirwj', false);
insert into USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, IS_ACTIVE) values ('Leeanne', 'Nelmes', 'Leeanne.Nelmes', 'bekiupnyho', false);

insert into TRAINEE (BIRTHDATE, ADDRESS, USER_ID) values ('2001-05-15', '6612 Rockefeller Lane', 1);
insert into TRAINEE (BIRTHDATE, ADDRESS, USER_ID) values ('1993-08-24', '234 American Point', 2);
insert into TRAINEE (BIRTHDATE, ADDRESS, USER_ID) values ('1990-11-25', '0899 Stone Corner Circle', 3);
insert into TRAINEE (BIRTHDATE, ADDRESS, USER_ID) values ('1994-05-08', '49065 Fordem Avenue', 4);
insert into TRAINEE (BIRTHDATE, ADDRESS, USER_ID) values ('1991-11-29', '1817 Marcy Alley', 5);
insert into TRAINEE (BIRTHDATE, ADDRESS, USER_ID) values ('1991-02-05', '0 Sommers Avenue', 6);
insert into TRAINEE (BIRTHDATE, ADDRESS, USER_ID) values ('1994-01-29', '62 Fieldstone Street', 7);
insert into TRAINEE (BIRTHDATE, ADDRESS, USER_ID) values ('2002-10-06', '6386 Dwight Terrace', 8);
insert into TRAINEE (BIRTHDATE, ADDRESS, USER_ID) values ('1997-03-23', '21779 Mendota Drive', 9);
insert into TRAINEE (BIRTHDATE, ADDRESS, USER_ID) values ('2002-06-21', '991 Kim Way', 10);
insert into TRAINEE (BIRTHDATE, ADDRESS, USER_ID) values ('1995-02-24', '75356 Di Loreto Parkway', 11);
insert into TRAINEE (BIRTHDATE, ADDRESS, USER_ID) values ('1997-10-01', '958 Gale Hill', 12);
insert into TRAINEE (BIRTHDATE, ADDRESS, USER_ID) values ('1999-06-09', '0 Roth Court', 13);
insert into TRAINEE (BIRTHDATE, ADDRESS, USER_ID) values ('1995-11-25', '38777 Miller Drive', 14);
insert into TRAINEE (BIRTHDATE, ADDRESS, USER_ID) values ('1998-02-09', '518 Scofield Street', 15);
insert into TRAINEE (BIRTHDATE, ADDRESS, USER_ID) values ('1999-06-26', '54 Melvin Avenue', 16);
insert into TRAINEE (BIRTHDATE, ADDRESS, USER_ID) values ('1995-12-17', '263 Crescent Oaks Lane', 17);
insert into TRAINEE (BIRTHDATE, ADDRESS, USER_ID) values ('1996-06-01', '24958 Kipling Terrace', 18);
insert into TRAINEE (BIRTHDATE, ADDRESS, USER_ID) values ('2004-03-15', '4 Vidon Pass', 19);
insert into TRAINEE (BIRTHDATE, ADDRESS, USER_ID) values ('1991-01-21', '926 Linden Court', 20);
insert into TRAINEE (BIRTHDATE, ADDRESS, USER_ID) values ('1991-03-21', '114 Melby Alley', 21);
insert into TRAINEE (BIRTHDATE, ADDRESS, USER_ID) values ('1990-10-02', '046 Northwestern Way', 22);
insert into TRAINEE (BIRTHDATE, ADDRESS, USER_ID) values ('1998-06-14', '9 Rutledge Street', 23);
insert into TRAINEE (BIRTHDATE, ADDRESS, USER_ID) values ('1996-07-29', '861 Stuart Parkway', 24);
insert into TRAINEE (BIRTHDATE, ADDRESS, USER_ID) values ('1998-01-04', '4949 Havey Hill', 25);

insert into TRAINING_TYPE (TRAINING_TYPE_NAME) values ('Fitness');
insert into TRAINING_TYPE (TRAINING_TYPE_NAME) values ('Yoga');
insert into TRAINING_TYPE (TRAINING_TYPE_NAME) values ('Zumba');
insert into TRAINING_TYPE (TRAINING_TYPE_NAME) values ('Stretching');
insert into TRAINING_TYPE (TRAINING_TYPE_NAME) values ('Resistance');

insert into TRAINER (SPECIALIZATION_ID, USER_ID) values (4, 26);
insert into TRAINER (SPECIALIZATION_ID, USER_ID) values (4, 27);
insert into TRAINER (SPECIALIZATION_ID, USER_ID) values (1, 28);
insert into TRAINER (SPECIALIZATION_ID, USER_ID) values (5, 29);
insert into TRAINER (SPECIALIZATION_ID, USER_ID) values (4, 30);
insert into TRAINER (SPECIALIZATION_ID, USER_ID) values (2, 31);
insert into TRAINER (SPECIALIZATION_ID, USER_ID) values (4, 32);
insert into TRAINER (SPECIALIZATION_ID, USER_ID) values (2, 33);
insert into TRAINER (SPECIALIZATION_ID, USER_ID) values (4, 34);
insert into TRAINER (SPECIALIZATION_ID, USER_ID) values (4, 35);
insert into TRAINER (SPECIALIZATION_ID, USER_ID) values (1, 36);
insert into TRAINER (SPECIALIZATION_ID, USER_ID) values (1, 37);
insert into TRAINER (SPECIALIZATION_ID, USER_ID) values (1, 38);
insert into TRAINER (SPECIALIZATION_ID, USER_ID) values (1, 39);
insert into TRAINER (SPECIALIZATION_ID, USER_ID) values (1, 40);
insert into TRAINER (SPECIALIZATION_ID, USER_ID) values (3, 41);
insert into TRAINER (SPECIALIZATION_ID, USER_ID) values (2, 42);
insert into TRAINER (SPECIALIZATION_ID, USER_ID) values (4, 43);
insert into TRAINER (SPECIALIZATION_ID, USER_ID) values (2, 44);
insert into TRAINER (SPECIALIZATION_ID, USER_ID) values (4, 45);
insert into TRAINER (SPECIALIZATION_ID, USER_ID) values (4, 46);
insert into TRAINER (SPECIALIZATION_ID, USER_ID) values (2, 47);
insert into TRAINER (SPECIALIZATION_ID, USER_ID) values (1, 48);
insert into TRAINER (SPECIALIZATION_ID, USER_ID) values (4, 49);
insert into TRAINER (SPECIALIZATION_ID, USER_ID) values (3, 50);

insert into TRAINEE2TRAINER (TRAINEE_ID, TRAINER_ID) values (25, 7);
insert into TRAINEE2TRAINER (TRAINEE_ID, TRAINER_ID) values (22, 17);
insert into TRAINEE2TRAINER (TRAINEE_ID, TRAINER_ID) values (18, 11);
insert into TRAINEE2TRAINER (TRAINEE_ID, TRAINER_ID) values (4, 2);
insert into TRAINEE2TRAINER (TRAINEE_ID, TRAINER_ID) values (10, 4);
insert into TRAINEE2TRAINER (TRAINEE_ID, TRAINER_ID) values (5, 14);
insert into TRAINEE2TRAINER (TRAINEE_ID, TRAINER_ID) values (5, 16);
insert into TRAINEE2TRAINER (TRAINEE_ID, TRAINER_ID) values (8, 9);
insert into TRAINEE2TRAINER (TRAINEE_ID, TRAINER_ID) values (11, 21);
insert into TRAINEE2TRAINER (TRAINEE_ID, TRAINER_ID) values (1, 3);
insert into TRAINEE2TRAINER (TRAINEE_ID, TRAINER_ID) values (6, 19);
insert into TRAINEE2TRAINER (TRAINEE_ID, TRAINER_ID) values (14, 7);
insert into TRAINEE2TRAINER (TRAINEE_ID, TRAINER_ID) values (4, 24);
insert into TRAINEE2TRAINER (TRAINEE_ID, TRAINER_ID) values (20, 17);
insert into TRAINEE2TRAINER (TRAINEE_ID, TRAINER_ID) values (22, 17);
insert into TRAINEE2TRAINER (TRAINEE_ID, TRAINER_ID) values (18, 9);
insert into TRAINEE2TRAINER (TRAINEE_ID, TRAINER_ID) values (23, 4);
insert into TRAINEE2TRAINER (TRAINEE_ID, TRAINER_ID) values (12, 16);
insert into TRAINEE2TRAINER (TRAINEE_ID, TRAINER_ID) values (16, 13);
insert into TRAINEE2TRAINER (TRAINEE_ID, TRAINER_ID) values (23, 20);
insert into TRAINEE2TRAINER (TRAINEE_ID, TRAINER_ID) values (24, 10);
insert into TRAINEE2TRAINER (TRAINEE_ID, TRAINER_ID) values (23, 17);
insert into TRAINEE2TRAINER (TRAINEE_ID, TRAINER_ID) values (19, 11);
insert into TRAINEE2TRAINER (TRAINEE_ID, TRAINER_ID) values (7, 9);
insert into TRAINEE2TRAINER (TRAINEE_ID, TRAINER_ID) values (3, 12);

insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (19, 25, 'Hard', 5, '2023-09-10', 94);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (5, 12, 'Extreme', 1, '2023-09-05', 48);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (20, 2, 'Easy', 3, '2023-07-28', 110);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (21, 12, 'Insane', 5, '2023-08-29', 46);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (22, 14, 'Extreme', 4, '2022-12-31', 33);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (17, 12, 'Normal', 5, '2023-04-28', 114);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (8, 22, 'Normal', 3, '2023-07-31', 54);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (10, 25, 'Easy', 4, '2023-07-05', 44);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (4, 24, 'Easy', 3, '2023-09-26', 99);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (21, 9, 'Normal', 1, '2023-05-03', 95);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (15, 23, 'Hard', 5, '2023-02-18', 52);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (20, 21, 'Easy', 3, '2023-09-01', 83);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (13, 19, 'Easy', 1, '2023-07-11', 62);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (1, 16, 'Normal', 3, '2023-03-24', 11);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (5, 9, 'Insane', 5, '2023-04-09', 33);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (21, 24, 'Normal', 5, '2023-07-20', 59);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (7, 20, 'Hard', 2, '2023-07-16', 95);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (22, 19, 'Easy', 2, '2023-08-11', 117);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (16, 20, 'Easy', 3, '2023-02-26', 38);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (11, 8, 'Extreme', 1, '2023-11-16', 55);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (17, 22, 'Hard', 1, '2023-04-23', 101);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (13, 21, 'Extreme', 2, '2023-08-06', 37);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (16, 16, 'Insane', 2, '2023-02-06', 82);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (1, 10, 'Normal', 1, '2023-12-11', 112);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (15, 18, 'Easy', 5, '2023-12-09', 78);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (8, 15, 'Hard', 2, '2023-09-13', 24);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (23, 12, 'Easy', 5, '2023-10-03', 29);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (10, 7, 'Easy', 3, '2023-01-09', 71);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (15, 9, 'Extreme', 1, '2023-09-13', 27);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (1, 14, 'Easy', 1, '2023-10-14', 97);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (10, 22, 'Normal', 4, '2023-08-22', 73);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (3, 2, 'Easy', 4, '2023-08-11', 17);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (10, 16, 'Easy', 5, '2023-08-09', 41);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (22, 9, 'Easy', 5, '2023-11-04', 104);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (8, 6, 'Easy', 1, '2023-01-15', 45);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (16, 10, 'Easy', 4, '2023-05-01', 110);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (23, 3, 'Normal', 3, '2023-11-04', 72);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (16, 18, 'Normal', 3, '2023-02-02', 45);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (12, 2, 'Hard', 1, '2023-11-03', 98);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (19, 7, 'Normal', 1, '2023-06-09', 5);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (15, 25, 'Hard', 1, '2023-11-02', 93);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (11, 13, 'Easy', 4, '2023-11-09', 117);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (4, 15, 'Hard', 3, '2023-06-12', 40);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (7, 1, 'Easy', 4, '2023-08-24', 84);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (1, 16, 'Normal', 1, '2023-09-03', 35);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (4, 5, 'Hard', 5, '2023-01-04', 80);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (3, 11, 'Easy', 4, '2023-07-17', 45);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (17, 8, 'Normal', 1, '2023-08-11', 83);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (2, 7, 'Normal', 4, '2023-10-26', 102);
insert into TRAINING (TRAINEE_ID, TRAINER_ID, TRAINING_NAME, TRAINING_TYPE_ID, TRAINING_DATE, TRAINING_DURATION) values (21, 21, 'Hard', 2, '2023-11-04', 18);